---
- name: Set Password
  hosts: main
  user: root
  become: yes
  ignore_errors: yes

  tasks:
   - name: Change siem Password
     user: name=siem update_password=always password=$1$SomeSalt$bV8bhWtZerRl2ACgzd7gC0

