---
 workgroup: SAMBA
 public_share_name: public
 public_share_path: /home/lanshare
 private_share_name: private
 private_share_path: /home/lanshare
 samba_group_name: smbgrp
 smaba_users:
  - { name: 'lanshare', smbpasswd: 'pass123' }
