---
- name: Set Password
  hosts: powertest
  user: root
  become: yes
  ignore_errors: yes

  tasks:
   - name: Change siem Password
     user: name=Siem update_password=always password=$2b$12$qDjgN9j4iPJ8/dx1Vqi0ceEAK7a7sZ8WBx95JH7YXwMtW29BRBF32

